name: 01-workflow-building-block

on: workflow_dispatch

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: this is first step
              run: echo " first job executed"
    second-job:
        runs-on: ubuntu-latest
        steps:
            - name: Good bye
              run: echo " So, Good bye both jobs executed well"
