# this work flow is designed to play with variables with a single work flow
name: 02-Variables-Workflow
run-name: 02-Variable-Workflow
on:
    push:
    workflow_dispatch:
env:
  WORKFLOW_VAR: I am a workflow variable
  OVERWRITTEN: I will be overritten
  
jobs:
    variable_job:
        runs-on: ubuntu-latest
        env:
          JOB_VAR: I am job env var
          OERWRITTEN: I have overritten at the job level

        steps:
            - name: play with variables
              env:
                STEP_VARIABLE: I am a steps variable 1
              run: |
                echo "Env Variable: ${{env.STEP_VARIABLE}}" 
                echo "Env Variable: ${{env.OVERWRITTEN}}" 
                echo "Env Variable: ${{env.JOB_VAR}}"
                echo "Env Variable: ${{env.WORKFLOW_VAR}}"  
            - name: var overritten
              evn:
                STEP-VARIABLE : I am step variable 2
                OVERWRITTEN: I have overritten at Step level
              run: |
                echo "Env Variable: ${{env.STEP_VARIABLE}}"
                echo "Env Variable: ${{env.OVERWRITTEN}}"