# this is context workflow of github
name: 02-Context

on:
    push:
    workflow_dispatch:

jobs:
    echo-data:
        runs-on: ubuntu-latest

        steps:
            - name: Display Information
              run: | 
                echo "event name ${{github.event_name}}"
                echo "ref ${{github.ref}}"
                echo "SHA ${{github.SHA}}"
